# 
# Synthesis run script generated by Vivado
# 

set_param simulator.vcsmxInstallPath /home/zcl/environment_soft/synopsys2016/vcs201809/bin
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zcl/test_architecture/vivado_project/function_library_sourcecode/test_plus64/test_plus64.cache/wt [current_project]
set_property parent.project_path /home/zcl/test_architecture/vivado_project/function_library_sourcecode/test_plus64/test_plus64.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_repo_paths /home/zcl/test_architecture/vivado_project/ip_repo/64plus [current_project]
set_property ip_output_repo /home/zcl/test_architecture/vivado_project/function_library_sourcecode/test_plus64/test_plus64.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/zcl/test_architecture/vivado_project/function_library_sourcecode/test_plus64/test_plus64.srcs/sources_1/imports/64plus/SimpleModule.v
  /home/zcl/test_architecture/vivado_project/function_library_sourcecode/test_plus64/test_plus64.srcs/sources_1/new/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7vx690tffg1761-2


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
